[project]
name = "football-works"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inference-gpu>=0.63.1",
    "ipykernel>=7.1.0",
    "ipython>=9.8.0",
    "rfdetr>=1.3.0",
]
